/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bookshops;

import Controler.Login;
import Controler.NewClass;

/**
 *
 * @author Hi! Hijaz
 */
public class Forgetpassword extends javax.swing.JFrame {

    static boolean pr3 = true;
    static boolean pr4 = true;

    /**
     * Creates new form Forgetpassword
     */
    public Forgetpassword() {
        initComponents();
        new NewClass().time(jLabel13);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        foget = new javax.swing.JPanel();
        jLabel3r = new javax.swing.JLabel();
        jLabel1r = new javax.swing.JLabel();
        jLabel2r = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1r = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jPasswordField1r = new javax.swing.JPasswordField();
        jTextField3r = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jTextField2r = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel3n3 = new javax.swing.JLabel();
        jPasswordField2r = new javax.swing.JPasswordField();
        jTextField4r = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel1n4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        foget.setBackground(new java.awt.Color(51, 51, 51));
        foget.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3r.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        jLabel3r.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3r.setText("Password");
        foget.add(jLabel3r, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 100, 20));

        jLabel1r.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        jLabel1r.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1r.setText("First Name");
        foget.add(jLabel1r, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, 20));

        jLabel2r.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        jLabel2r.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2r.setText("Last Name");
        foget.add(jLabel2r, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 100, 20));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/eye_16px.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        foget.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, -1, 30));

        jTextField1r.setBackground(new java.awt.Color(51, 51, 51));
        jTextField1r.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1r.setForeground(new java.awt.Color(240, 240, 240));
        jTextField1r.setBorder(null);
        jTextField1r.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1r.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextField1r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1rActionPerformed(evt);
            }
        });
        foget.add(jTextField1r, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 360, 30));
        foget.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 360, -1));

        jPasswordField1r.setBackground(new java.awt.Color(51, 51, 51));
        jPasswordField1r.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jPasswordField1r.setForeground(new java.awt.Color(240, 240, 240));
        jPasswordField1r.setBorder(null);
        jPasswordField1r.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPasswordField1r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1rActionPerformed(evt);
            }
        });
        jPasswordField1r.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1rKeyReleased(evt);
            }
        });
        foget.add(jPasswordField1r, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 360, 40));

        jTextField3r.setBackground(new java.awt.Color(51, 51, 51));
        jTextField3r.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField3r.setForeground(new java.awt.Color(240, 240, 240));
        jTextField3r.setBorder(null);
        jTextField3r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3rActionPerformed(evt);
            }
        });
        foget.add(jTextField3r, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 360, 40));
        foget.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 360, -1));

        jTextField2r.setBackground(new java.awt.Color(51, 51, 51));
        jTextField2r.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField2r.setForeground(new java.awt.Color(240, 240, 240));
        jTextField2r.setBorder(null);
        jTextField2r.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField2r.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextField2r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2rActionPerformed(evt);
            }
        });
        foget.add(jTextField2r, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 360, 30));
        foget.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 360, -1));

        jLabel3n3.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        jLabel3n3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3n3.setText("Conform Password");
        foget.add(jLabel3n3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 140, 20));

        jPasswordField2r.setBackground(new java.awt.Color(51, 51, 51));
        jPasswordField2r.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jPasswordField2r.setForeground(new java.awt.Color(240, 240, 240));
        jPasswordField2r.setBorder(null);
        jPasswordField2r.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPasswordField2r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2rActionPerformed(evt);
            }
        });
        jPasswordField2r.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField2rKeyReleased(evt);
            }
        });
        foget.add(jPasswordField2r, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 360, 40));

        jTextField4r.setBackground(new java.awt.Color(51, 51, 51));
        jTextField4r.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField4r.setForeground(new java.awt.Color(240, 240, 240));
        jTextField4r.setBorder(null);
        jTextField4r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4rActionPerformed(evt);
            }
        });
        foget.add(jTextField4r, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 360, 40));
        foget.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 360, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/eye_16px.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        foget.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, -1, 30));

        jLabel1n4.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        jLabel1n4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1n4.setText("First Name");
        foget.add(jLabel1n4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, 20));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 153, 153));
        jButton2.setText("save");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.setContentAreaFilled(false);
        jButton2.setVerifyInputWhenFocusTarget(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        foget.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 290, 30));

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Log in");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        foget.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, -1, -1));

        getContentPane().add(foget, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 500, 570));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("jLabel13");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 230, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Log In");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 230, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/cancel_24px.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel16MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
        });
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, -1, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 30));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/bookshop.jpg"))); // NOI18N
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 200, 200));

        jLabel17.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("HHA BookShop");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 230, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 500, 570));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1000)/2, (screenSize.height-600)/2, 1000, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
       new Login().pas(jPasswordField2r, jTextField4r, jTextField1r, jLabel10);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jTextField1rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1rActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1rActionPerformed

    private void jPasswordField1rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1rActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1rActionPerformed

    private void jPasswordField1rKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1rKeyReleased
        jTextField3r.setText(jPasswordField1r.getText());
        jTextField3r.setVisible(false);
        jTextField4r.setVisible(false);
    }//GEN-LAST:event_jPasswordField1rKeyReleased

    private void jTextField3rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3rActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3rActionPerformed

    private void jTextField2rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2rActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2rActionPerformed

    private void jPasswordField2rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2rActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2rActionPerformed

    private void jPasswordField2rKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2rKeyReleased
        jTextField4r.setText(jPasswordField2r.getText());
        jTextField3r.setVisible(false);
        jTextField4r.setVisible(false);
    }//GEN-LAST:event_jPasswordField2rKeyReleased

    private void jTextField4rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4rActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4rActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        new Login().pas(jPasswordField1r, jTextField3r, jTextField3r, jLabel12);
        
       
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Login().reset(jTextField1r, jTextField2r, jTextField3r, jTextField4r);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseExited

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/cancel_24px.png")));


    }//GEN-LAST:event_jLabel16MouseExited

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/cancelr_24px.png")));
    }//GEN-LAST:event_jLabel16MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forgetpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forgetpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forgetpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forgetpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Forgetpassword().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel foget;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel1n4;
    private javax.swing.JLabel jLabel1r;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2r;
    private javax.swing.JLabel jLabel3n3;
    private javax.swing.JLabel jLabel3r;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1r;
    private javax.swing.JPasswordField jPasswordField2r;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField1r;
    private javax.swing.JTextField jTextField2r;
    private javax.swing.JTextField jTextField3r;
    private javax.swing.JTextField jTextField4r;
    // End of variables declaration//GEN-END:variables
}
