/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bookshops;
import Controler.Login;
import Controler.NewClass;
/**
 *
 * @author Hi! Hijaz
 */
public class newuser extends javax.swing.JFrame {
static boolean pr1 = true;
    static boolean pr2 = true;
    /**
     * Creates new form newuser
     */
    public newuser() {
        initComponents();
        new NewClass().time(jLabel13);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        newuser = new javax.swing.JPanel();
        jLabel3n = new javax.swing.JLabel();
        jLabel2n = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPasswordField1n = new javax.swing.JPasswordField();
        jTextField3n = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jTextField2n = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel3n1 = new javax.swing.JLabel();
        jPasswordField2n = new javax.swing.JPasswordField();
        jTextField4n = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel1n2 = new javax.swing.JLabel();
        jTextField1n = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("jLabel13");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 230, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Log In");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 230, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/cancel_24px.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
        });
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, -1, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 30));

        newuser.setBackground(new java.awt.Color(51, 51, 51));
        newuser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3n.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        jLabel3n.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3n.setText("Password");
        newuser.add(jLabel3n, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 100, 20));

        jLabel2n.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        jLabel2n.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2n.setText("User Name");
        newuser.add(jLabel2n, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 100, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/eye_16px.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        newuser.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, -1, 30));

        jPasswordField1n.setBackground(new java.awt.Color(51, 51, 51));
        jPasswordField1n.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPasswordField1n.setForeground(new java.awt.Color(240, 240, 240));
        jPasswordField1n.setBorder(null);
        jPasswordField1n.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPasswordField1n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1nActionPerformed(evt);
            }
        });
        jPasswordField1n.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1nKeyReleased(evt);
            }
        });
        newuser.add(jPasswordField1n, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 360, 40));

        jTextField3n.setBackground(new java.awt.Color(51, 51, 51));
        jTextField3n.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField3n.setForeground(new java.awt.Color(240, 240, 240));
        jTextField3n.setBorder(null);
        jTextField3n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3nActionPerformed(evt);
            }
        });
        newuser.add(jTextField3n, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 360, 40));
        newuser.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 360, -1));

        jTextField2n.setBackground(new java.awt.Color(51, 51, 51));
        jTextField2n.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField2n.setForeground(new java.awt.Color(240, 240, 240));
        jTextField2n.setBorder(null);
        jTextField2n.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField2n.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextField2n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2nActionPerformed(evt);
            }
        });
        newuser.add(jTextField2n, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 360, 30));
        newuser.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 360, -1));

        jLabel3n1.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        jLabel3n1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3n1.setText("Conform Password");
        newuser.add(jLabel3n1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 140, 20));

        jPasswordField2n.setBackground(new java.awt.Color(51, 51, 51));
        jPasswordField2n.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jPasswordField2n.setForeground(new java.awt.Color(240, 240, 240));
        jPasswordField2n.setBorder(null);
        jPasswordField2n.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPasswordField2n.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField2nKeyReleased(evt);
            }
        });
        newuser.add(jPasswordField2n, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 360, 40));

        jTextField4n.setBackground(new java.awt.Color(51, 51, 51));
        jTextField4n.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField4n.setForeground(new java.awt.Color(240, 240, 240));
        jTextField4n.setBorder(null);
        jTextField4n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4nActionPerformed(evt);
            }
        });
        newuser.add(jTextField4n, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 360, 40));
        newuser.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 360, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/eye_16px.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        newuser.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, 30));

        jLabel1n2.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        jLabel1n2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1n2.setText("Staff ID");
        newuser.add(jLabel1n2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 120, 20));

        jTextField1n.setBackground(new java.awt.Color(51, 51, 51));
        jTextField1n.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1n.setForeground(new java.awt.Color(240, 240, 240));
        jTextField1n.setBorder(null);
        jTextField1n.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1n.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextField1n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1nActionPerformed(evt);
            }
        });
        newuser.add(jTextField1n, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 360, 30));
        newuser.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 360, -1));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 153, 153));
        jButton3.setText("save");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.setContentAreaFilled(false);
        jButton3.setVerifyInputWhenFocusTarget(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        newuser.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 290, 30));

        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Log in");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        newuser.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, 40, 20));

        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        newuser.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 530, 30));

        getContentPane().add(newuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 500, 570));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/bookshop.jpg"))); // NOI18N
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 200, 200));

        jLabel17.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("HHA BookShop");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 230, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 500, 570));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1000)/2, (screenSize.height-600)/2, 1000, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
       new Login().pas(jPasswordField2n, jTextField4n, jTextField4n, jLabel9);
        
        
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jPasswordField1nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1nActionPerformed

    private void jPasswordField1nKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1nKeyReleased
        jTextField3n.setText(jPasswordField1n.getText());
        jTextField3n.setVisible(false);
        jTextField4n.setVisible(false);

    }//GEN-LAST:event_jPasswordField1nKeyReleased

    private void jTextField3nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3nActionPerformed

    private void jTextField2nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2nActionPerformed

    private void jPasswordField2nKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2nKeyReleased
        jTextField4n.setText(jPasswordField2n.getText());
        jTextField3n.setVisible(false);
        jTextField4n.setVisible(false);

    }//GEN-LAST:event_jPasswordField2nKeyReleased

    private void jTextField4nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4nActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
       new Login().pas(jPasswordField1n, jTextField3n, jTextField3n, jLabel11);
        
       
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jTextField1nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1nActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Login().save(jTextField1n, jTextField2n, jTextField3n, jTextField4n, jLabel16);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        
       new login().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
       
            jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/cancel_24px.png")));
       


    }//GEN-LAST:event_jLabel12MouseExited

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/cancelr_24px.png")));
    }//GEN-LAST:event_jLabel12MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new newuser().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel1n2;
    private javax.swing.JLabel jLabel2n;
    private javax.swing.JLabel jLabel3n;
    private javax.swing.JLabel jLabel3n1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1n;
    private javax.swing.JPasswordField jPasswordField2n;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTextField1n;
    private javax.swing.JTextField jTextField2n;
    private javax.swing.JTextField jTextField3n;
    private javax.swing.JTextField jTextField4n;
    private javax.swing.JPanel newuser;
    // End of variables declaration//GEN-END:variables
}
